FROM python:3.6-alpine

# INSTALL PYTHON
ADD requirements.txt /requirements.txt

RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
            gcc \
            make \
            libc-dev \
            musl-dev \
            linux-headers \
            pcre-dev \
            postgresql-dev \
            libffi \
            libffi-dev \
            jpeg-dev \
            zlib-dev \
            libxml2 \
            libxml2-dev \
            python-dev \
            libxslt-dev \
    && pyvenv /venv \
    && /venv/bin/pip install -U pip \
    && LIBRARY_PATH=/lib:/usr/lib /bin/sh -c "/venv/bin/pip install --no-cache-dir -r /requirements.txt" \
    && runDeps="$( \
            scanelf --needed --nobanner --recursive /venv \
                    | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
                    | sort -u \
                    | xargs -r apk info --installed \
                    | sort -u \
    )" \
    && apk add --no-cache --virtual .python-rundeps $runDeps \
    && LIBRARY_PATH=/lib:/usr/lib /bin/sh -c "/venv/bin/pip install --no-cache-dir dumb-init" \
    && apk del .build-deps \
    && apk add --no-cache postgresql-client

RUN mkdir /code/
WORKDIR /code/
ADD . /code/

EXPOSE 8080

ENTRYPOINT ["/venv/bin/dumb-init", "--", "/venv/bin/python", "/code/issue_tracker/manage.py"]
CMD ["runserver", "0.0.0.0:8080"]
