# Generated by Django 2.0 on 2018-06-18 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the issue.', max_length=254, verbose_name='Name')),
                ('state', models.CharField(choices=[('ass', 'Assigned'), ('don', 'Done'), ('can', 'Canceled.'), ('cre', 'Created.')], default='cre', help_text='The state of the issue.', max_length=4, verbose_name='State')),
                ('description', models.TextField(help_text='The description of the issue.', verbose_name='Description')),
                ('completed_in', models.DurationField(blank=True, help_text='The time duration in which the task was completed.', null=True, verbose_name='Completed in')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
        ),
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the issue category.', max_length=254, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Issue category',
                'verbose_name_plural': 'Issue categories',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The category of the issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.IssueCategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='issue',
            name='created_by',
            field=models.ForeignKey(help_text='The person which created the issue.', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='issue',
            name='solver',
            field=models.ForeignKey(blank=True, help_text='The assigned solver of this issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solving_issues', to=settings.AUTH_USER_MODEL, verbose_name='Solver'),
        ),
    ]
