# Generated by Django 2.0 on 2018-06-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assiged at'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='state',
            field=models.CharField(choices=[('ass', 'Assigned'), ('don', 'Done'), ('can', 'Canceled'), ('cre', 'Created')], default='cre', help_text='The state of the issue.', max_length=4, verbose_name='State'),
        ),
    ]
